language: r
cache: packages
r:
  - oldrel
  - release
  - devel
warnings_are_errors: TRUE
notifications:
  email:
    on_success: change
    on_failure: always
after_error:
  - ./travis-tool.sh dump_logs
after_failure:
  - cat ~/r-source/config.log || true